version: "3"
services:
  backend:
    build: ./backend
    container_name: myapp-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: myapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

